### ISSUE TITLE
events: add create/delete branch, pushes 0 commits

### ISSUE THREAD

**Issue by TheRealJP** [YappyBots/YappyGitLab#18]
Currently displays: 
![delete_branch](https://user-images.githubusercontent.com/8147638/31309951-ffac2632-ab5c-11e7-9c97-224429cda9ea.png)

**Comment by datitisev** [comment]
I'll do the create/delete event tomorrow. I've currently removed the `pushed 0 commits` message. 🙂

**Comment by datitisev** [comment]
Seems like Gitlab pushes 0 commits whenever a branch is created/deleted, but no actual event. I'll close this, as Gitlab doesn't emit any event after  creating/closing a branch except `push`.
If this is wanted, however, I can still make it. 🙂
