### ISSUE TITLE
event: Initorg support for private projects

### ISSUE THREAD

**Issue by TheRealJP** [YappyBots/YappyGitLab#22]
```javascript
    return Gitlab.getGroupProjects(orgName).then(async data => {
      const conf = ChannelConfig.get(channelid) || await ChannelConfig.add(msg.channel);
      const repos = data.body.filter(e => !e.private && !conf.repos.includes(e.name_with_namespace.toLowerCase())).map(e => e.name_with_namespace);

      return Promise.all(repos.map(repo => ChannelConfig.addRepoToChannel(channelid, repo))).then(() => repos);
    })
```
 Perhaps a private parameter similar to the init command?

**Comment by datitisev** [comment]
Even if it had an argument, the bot still wouldn't be able to see the list of private projects in an organization. If you give me permission to see the organization (maybe as guest), then it would find them.
I tried to look if I could create a "bot account" in Gitlab, but that doesn't seem be possible. So I either create a second account just for the bot, and never actually access it, or you have to give me permission to read it.
Very inconvenient 😕

**Comment by datitisev** [comment]
Doesn't seem possible. Only way is to give me (datitisev) permission to view the repository.

**Comment by datitisev** [comment]
see https://github.com/YappyBots/YappyGitLab/commit/a1c2bcb05e7fcbb797b6d60d4cd5e3870fe5572c
