### ISSUE TITLE
Error with webhooks

### ISSUE THREAD

**Issue by Yehonal** [YappyBots/YappyGitLab#39]
Hello guys, this morning i've error with an hook that always worked:

> Hook executed successfully but returned HTTP 500 TypeError: e.repos.filter is not a function at _data.filter.e (lib/Models/ChannelConfig.js:169:43) at Map.filter (node_modules/discord.js/src/util/Collection.js:274:11) at ChannelConfig.findByRepo (lib/Models/ChannelConfig.js:169:23) at app.post (lib/Web.js:50:34) at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5) at next (node_modules/express/lib/router/route.js:137:13) at Route.dispatch (node_modules/express/lib/router/route.js:112:3) at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5) at /root/YappyGitlab/node_modules/express/lib/router/index.js:281:22 at Function.process_params (node_modules/express/lib/router/index.js:335:12) at next (node_modules/express/lib/router/index.js:275:10) at app.use (lib/Web.js:29:3) at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5) at trim_prefix (node_modules/express/lib/router/index.js:317:13) at /root/YappyGitlab/node_modules/express/lib/router/index.js:284:7 at Function.process_params (node_modules/express/lib/router/index.js:335:12)

Could someone help me?

**Comment by martinhyland** [comment]
Can reproduce

however error `500` would indicate its an issue with the web hook receiver on the bots end not gitlab or your end, you'll just have to wait for it to be fixed.

Here is the error one more time without the weird formatting:
```JSON
TypeError: e.repos.filter is not a function
    at _data.filter.e (lib/Models/ChannelConfig.js:169:43)
    at Map.filter (node_modules/discord.js/src/util/Collection.js:274:11)
    at ChannelConfig.findByRepo (lib/Models/ChannelConfig.js:169:23)
    at app.post (lib/Web.js:50:34)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at next (node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at /root/YappyGitlab/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (node_modules/express/lib/router/index.js:335:12)
    at next (node_modules/express/lib/router/index.js:275:10)
    at app.use (lib/Web.js:29:3)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (node_modules/express/lib/router/index.js:317:13)
    at /root/YappyGitlab/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (node_modules/express/lib/router/index.js:335:12)```

**Comment by leodrummond** [comment]
I can also reproduce the same error. The bot no longer sends repo updates to the configured Discord channel.

**Comment by axd2201** [comment]
I am also having the same problem, here is my error

`Hook executed successfully but returned HTTP 500 TypeError: e.repos.filter is not a function at _data.filter.e (lib/Models/ChannelConfig.js:169:43) at Map.filter (node_modules/discord.js/src/util/Collection.js:274:11) at ChannelConfig.findByRepo (lib/Models/ChannelConfig.js:169:23) at app.post (lib/Web.js:50:34) at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5) at next (node_modules/express/lib/router/route.js:137:13) at Route.dispatch (node_modules/express/lib/router/route.js:112:3) at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5) at /root/YappyGitlab/node_modules/express/lib/router/index.js:281:22 at Function.process_params (node_modules/express/lib/router/index.js:335:12) at next (node_modules/express/lib/router/index.js:275:10) at app.use (lib/Web.js:29:3) at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5) at trim_prefix (node_modules/express/lib/router/index.js:317:13) at /root/YappyGitlab/node_modules/express/lib/router/index.js:284:7 at Function.process_params (node_modules/express/lib/router/index.js:335:12)`

**Comment by LenneRoijmans** [comment]
Can confirm, bot not functional at the moment

**Comment by devingDev** [comment]
seems like everyone has this issue right now, so be patient and hope for the best

**Comment by datitisev** [comment]
Sorry, trying to fix.

**Comment by datitisev** [comment]
Seems like it's working now. My apologies.

If you have any bugs that occur spontaneously like this one, please join the Discord server if you can so you can get help from other people or await my response. Link can be found in the README.

Closing for now. I may have to make a weird DB refactor to fix whatever the hell goes on here.
