### ISSUE TITLE
Notifications design broken

### ISSUE THREAD

**Issue by Romain-P** [YappyBots/YappyGitLab#46]
Hello,

I invited the bot and then did in order
 * `GL! invit https://gitlab.com/my_repo private`

After this, I receive notifications on my discord channel with beautiful messages wrapped by a square and colors.  
After doing the following commands:
 * `GL! conf events enable merge_requests/update`
 * `GL! conf events enable pipeline`

All events are enabled and the notifications design is not the same. It's only texts without any design. Is this intended or is this a bug?

Cheers

**Comment by datitisev** [comment]
Hello @Romain-P. For issues like this, it's probably best to ask on the Discord server (https://www.yappybots.tk/#/discord).

It might be an issue that simply required restarting the bot. Though you say you never configured the embed style (that's what it is called), so perhaps try running `GL! conf set embed true`.
