### ISSUE TITLE
Error with command mr list -> [ERR_STREAM_WRITE_AFTER_END]

### ISSUE THREAD

**Issue by Daniel-Mendes** [YappyBots/YappyGitLab#58]
**To reproduce the error:**
`GL! mr list`
**Result:**
![Yappy-issue](https://user-images.githubusercontent.com/28825568/78329264-81f88400-7581-11ea-89a6-9cf0f24d711c.png)

I'm on private repository, I don't know if it's change something.

**Comment by datitisev** [comment]
That error sounds not occur, but in its place you'd find a not found error - you can't list repo info if the repo is private, no access to it.

**Comment by Daniel-Mendes** [comment]
@datitisev ohh oke thanks, can i add maybe a private access token for the bot gain access to my private repositories ?

**Comment by datitisev** [comment]
@Daniel-Mendes Not right now, sorry. And I may not allow that in the future either, not sure I want to store access tokens at all.

**Comment by Daniel-Mendes** [comment]
Oke so i think is the same problem why i have a 501 error, when trying to access https://www.yappybots.tk/gitlab/dashboard/guilds/xxx of a private repository ?

**Comment by datitisev** [comment]
Not sure... it works for me.

**Comment by Daniel-Mendes** [comment]
I will try with other repository, thank for the quick response. I close the issue !
