### ISSUE TITLE
Use total_commits_count to display number of commits pushed

### ISSUE THREAD

**Issue by mutezero** [YappyBots/YappyGitLab#63]
GitLab 12.1.1 sends 20 commit messages at max (in the `commits` array).  
When a number of commits pushed is greater than 20, Yappy would report `"Pushed 20 commits to {branch}"`.  
An actual number of commits is described in the `total_commits_count` field of the `push` message.

**Comment by datitisev** [comment]
Fixed with 843c099b1cdcff7440b6e959c0123c22549274b3
